# To start all docker containers run: `docker-compose up`
#
version: '3.8'
services:
  app:
    build:
      context: .
      target: develop
    command: bash -c "bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app
      - gem_cache:/gems
      - cache:/cache #Added to support Window 10 Docker
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - SMTP_HOST=mailcatcher
#      - LDAP_HOST=ldap
      - SPROCKETS_CACHE=/cache #Added to support Window 10 Docker
    tty: true
    stdin_open: true
  delayed_job:
    build:
      context: .
      target: develop
    command: bundle exec rake jobs:work
    depends_on:
      - app
    volumes:
      - .:/app
      - gem_cache:/gems
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - SMTP_HOST=mailcatcher
    stdin_open: true
    tty: true
  db:
    image: mysql:5.7.22
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    logging:
      driver: none
  mailcatcher:
    build: .
    command: bash -c "gem install mailcatcher && mailcatcher --ip 0.0.0.0 --no-quit -f"
    ports:
      - "1080:1080"
    volumes:
      - .:/app
      - gem_cache:/gems
    tty: true
    stdin_open: true
#  ldap:
#    image: osixia/openldap
#    command: "--copy-service"
#    ports:
#      - "389:389"
#    volumes:
#      - "ldap-data:/var/lib/ldap"
#      - "slapd-config:/etc/ldap/slapd.d"
      # Loads some default users into the database
#      - "./vendor/engines/ldap_authentication/spec/fixtures:/container/service/slapd/assets/config/bootstrap/ldif/custom"

  # Optional administrative website
#  ldap-admin:
#    image: osixia/phpldapadmin
#    ports:
#      - "8081:80"
#    depends_on:
#      - ldap
#    environment:
#      - PHPLDAPADMIN_LDAP_HOSTS=ldap
#      - PHPLDAPADMIN_HTTPS=false
    
volumes:
  cache: #Added to support Window 10 Docker
  db-data:
    driver: local
  gem_cache: {}
#  slapd-config:
#    driver: local
#  ldap-data:
#    driver: local
